### ISSUE TITLE
sh: 30: set: Illegal option -o pipefail

### ISSUE THREAD

**Issue by pnfcre** [zeit/install-node#3]
Hi there,

I'm trying to run `curl -sL install-node.now.sh/lts | sh` from my Linux machine, but it errors with `sh: 30: set: Illegal option -o pipefail`.

Kind regards,
Casper.

**Comment by pnfcre** [comment]
Nevermind, I had to change `sh` to `bash`!

**Comment by mjarosie** [comment]
Could this solution be added to README or even somehow checked automatically? I've run into the same issue and that'd be really helpful to get some kind of feedback from the script : )
